version: '3.7'

volumes:
  no_back_postgres_data:
  cache:
    driver: local

networks:
  main-network:
    name: main-network

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  db:
    image: postgres
    container_name: postgres-db
    volumes:
      - no_back_postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file:
      - ./backend/env/dev.db.env
    networks:
      - main-network
    restart: always

  pgadmin:
    #    https://dev.to/mojemoron/how-to-connect-your-django-app-to-a-dockerized-postgresql-and-pgadmin-133o
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    env_file:
      - ./backend/env/dev.pgAdmin.env
    restart: always
    networks:
      - main-network
