version: '3.7'

volumes:
  dev_postgres_data:

networks:
  main-network:
    external: true
    name: main-network

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - main-network
    restart: always

  db:
    image: postgres:12.0-alpine
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data/
    ports:
      - '1396:5432'
    env_file:
      - ./backend/dev.db.env
    networks:
      - main-network
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: gunicorn backend.root.asgi:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8002
    env_file:
      - ./backend/dev.env
    depends_on:
      - db
      - redis
    ports:
      - "8002:8002"
    networks:
      - main-network
    restart: always



