version: '3.7'

volumes:
  dev_postgres_data:
  cache:
    driver: local

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data


  db:
    image: postgres
    container_name: postgres-db
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file:
      - ./backend/env/dev.db.env
    networks:
      - main-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    env_file:
      - ./backend/env/dev.pgAdmin.env
    restart: always
    networks:
      - main-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: gunicorn backend.config.asgi:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8002
    env_file:
      - ./backend/env/dev.env
    depends_on:
      - db
      - redis
    ports:
      - "8002:8002"
    networks:
      - main-network
    restart: always

networks:
  main-network:
    name: main-network
    driver: bridge