version: '3.7'

volumes:
  no_back_postgres_data:

networks:
  main-network:
    name: main-network

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - main-network
    restart: always

  db:
    image: postgres
    container_name: postgres-db
    volumes:
      - no_back_postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file:
      - ./backend/env/dev.db.env
    networks:
      - main-network
    restart: always

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      depends_on:
        - db
      ports:
        - "5051:80"
      env_file:
        - ./backend/env/dev.pgAdmin.env
      restart: always
      networks:
        - main-network
