version: '3.7'

volumes:
  no_back_postgres_data:

networks:
  main-network:
    name: main-network

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - main-network
    restart: always

  db:
    image: postgres:12.0-alpine
    volumes:
      - no_back_postgres_data:/var/lib/postgresql/data/
    ports:
      - '1396:5432'
    env_file:
      - ./backend/dev.db.env
    networks:
      - main-network
    restart: always


